mod character;
pub mod collection;
pub mod crafting;
mod glamour;
pub mod home;
pub mod inventory;
pub mod notes;
pub mod settings;
mod settings_resources;
pub mod weapon_models;

pub use character::CharacterPage;
pub use collection::CollectionPage;
pub use crafting::CraftingPage;
pub use glamour::GlamourPage;
pub use home::HomePage;
pub use inventory::InventoryPage;
pub use notes::NotesPage;
pub use settings::SettingsPage;
pub use weapon_models::ModelPreviewPage;
